name: First workflow

on: 
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: hello message
        run: echo "Welcome LOL :)"

      - name: checkout repo
        uses: actions/checkout@v5.0.0

      - name: list repo files
        run: ls -al
